# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'TalkTalk' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for TalkTalk
  
  pod ‘Firebase/Core’
  pod ‘Firebase/Auth’
  pod ‘Firebase/Database’
  pod ‘Firebase/Storage’
  pod 'JSQMessagesViewController', :git => 'https://github.com/jessesquires/JSQMessagesViewController.git', :branch => 'develop'
  pod 'ChameleonFramework/Swift', :git => 'https://github.com/ViccAlexander/Chameleon.git'
  
  target 'TalkTalkTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
